export const sales = [
  {
    "id":1,
    "orderNumber": "ORD001",
    "customerName": "John Doe",
    "product": "Product A",
    "quantity": 5,
    "unitPrice": 50,
    "totalAmount": 250,
    "soldDate": "2021-09-20",
  },
  {
    "id":2,
    "orderNumber": "ORD002",
    "customerName": "Jane Smith",
    "product": "Product B",
    "quantity": 3,
    "unitPrice": 40,
    "totalAmount": 120,
    "soldDate": "2021-09-12",
  },
  {
    "id":3,
    "orderNumber": "ORD003",
    "customerName": "Alice Johnson",
    "product": "Product C",
    "quantity": 2,
    "unitPrice": 30,
    "totalAmount": 60,
    "soldDate": "2021-09-12",
  },
  {
    "id":4,
    "orderNumber": "ORD003",
    "customerName": "Alice Johnson",
    "product": "Product C",
    "quantity": 2,
    "unitPrice": 30,
    "totalAmount": 60,
    "soldDate": "2021-09-20",
  }
]